### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by anyb1s** [appstract/laravel-bootstrap-components#4]
Hello,

Will there be a form component, it exists in the docs but the view is missing?

Thanks.

P.S. Really love the package!

**Comment by vpratfr** [comment]
Hi,

Created that one: https://github.com/marvinlabs/laravel-html-bootstrap-4 for that reason.

An extension to Spatie's laravel-html package with all the goodness of Adam Wathan's  bootforms package and incorporating little by little some components from this package :)
