### ISSUE TITLE
null coalesce operator

### ISSUE THREAD

**Issue by ediblemanager** [appstract/laravel-bootstrap-components#6]
With Laravel 5.7, the `or` operator in blade files has been switched out in favour of PHP's null coalesce operator, meaning that it errors when running this package.

Since PHP 7 supports the `??` syntax (and Laravel since 5.5), could there be a branch for 5.5+ and one for <5.5?

**Comment by ediblemanager** [comment]
Added PR: https://github.com/appstract/laravel-bootstrap-components/pull/7

**Comment by gizburdt** [comment]
Merged! :)

**Comment by ediblemanager** [comment]
Sorry to re-open, but I'm wondering if you know when packagist will update with the latest code? I could add the repo via github in `composer.json`, but would prefer to not take that step if it will appear on packagist soon!

**Comment by gizburdt** [comment]
Packagist changed something in the Github connection. I re-enabled it, so it should work now :)
